

services:
  chromadb:
    image: chromadb/chroma:latest
    # 1. Enforces the same container name every single time it boots
    container_name: intelligent-pdf-rag-chromadb
    ports:
      - "8000:8000"
    volumes:
      # Maps your local host folder to the internal data folder
      - ./chroma_data:/data
    environment:
      - IS_PERSISTENT=TRUE
      # Point the database engine compiler target to read from /data
      - PERSIST_DIRECTORY=/data
      - ANONYMOUS_TELEMETRY=FALSE
    # Ensures the container runs with root permissions internally to fluidly write to your local ./chroma_data folder
    user: "root"
    restart: always